import { ScreenType, UserRole } from '@/src/types.ts';

export interface ScreenMeta {
  id: ScreenType;
  title: string;
  shortTitle: string;
  audience: 'guest' | 'user' | 'both';
  category: string;
  description: string;
  icon: string;
}

export const SCREEN_CONFIGS: Record<ScreenType, ScreenMeta> = {
  'platform-features': {
    id: 'platform-features',
    title: 'Tính Năng Nền Tảng · Gia Phả Toàn Diện',
    shortTitle: 'Tính năng',
    audience: 'guest',
    category: 'Giới thiệu',
    description: 'Khám phá các công cụ lưu giữ gia phả, ký ức và gia phong.',
    icon: 'auto_awesome',
  },
  'privacy-security': {
    id: 'privacy-security',
    title: 'Bảo Mật Ký Ức Gia Tộc & Quyền Riêng Tư',
    shortTitle: 'Bảo mật',
    audience: 'guest',
    category: 'Giới thiệu',
    description: 'Bảo vệ dữ liệu gia tộc bằng phân quyền, mã hóa và kiểm soát minh bạch.',
    icon: 'shield_lock',
  },
  'pricing': {
    id: 'pricing',
    title: 'Bảng Giá Phụng Sự · Đầu Tư Trọn Vẹn Cho Ký Ức Gia Tộc',
    shortTitle: 'Bảng giá',
    audience: 'guest',
    category: 'Giới thiệu',
    description: 'Chọn cách bắt đầu phù hợp với quy mô và nhu cầu lưu giữ của gia đình.',
    icon: 'payments',
  },  'guest-landing': {
    id: 'guest-landing',
    title: 'Chào Mừng Đến Với Thích Cúng Kiếng',
    shortTitle: 'Trang Guest',
    audience: 'guest',
    category: 'Khởi đầu',
    description: 'Trang đón khách, giới thiệu di sản và các lối vào không gian dòng họ.',
    icon: 'temple_buddhist',
  },
  'today': {
    id: 'today',
    title: 'Hôm Nay',
    shortTitle: 'Hôm nay',
    audience: 'user',
    category: 'Không gian thành viên',
    description: 'Tóm tắt việc cần làm, ngày giỗ và hoạt động mới trong dòng họ.',
    icon: 'today',
  },
  'family-calendar': {
    id: 'family-calendar',
    title: 'Lịch Gia Đình',
    shortTitle: 'Lịch gia đình',
    audience: 'user',
    category: 'Không gian thành viên',
    description: 'Theo dõi ngày giỗ, lễ họ và các mốc quan trọng của gia đình.',
    icon: 'calendar_month',
  },  // === NHÓM GUEST (Dành cho khách vãng lai, người mới, chưa đăng nhập) ===
  'login': {
    id: 'login',
    title: 'Đăng Nhập Không Gian Gia Tộc',
    shortTitle: 'Đăng nhập',
    audience: 'guest',
    category: 'Xác thực & Tiếp cận',
    description: 'Dành cho khách hoặc con cháu truy cập tài khoản phả hệ đã có.',
    icon: 'login',
  },
  'register': {
    id: 'register',
    title: 'Đăng Ký Thành Viên / Lập Phả Mới',
    shortTitle: 'Đăng ký lập phả',
    audience: 'guest',
    category: 'Xác thực & Tiếp cận',
    description: 'Dành cho khách muốn gia nhập chi tộc hoặc đăng ký dòng họ mới.',
    icon: 'how_to_reg',
  },
  'forgot-password': {
    id: 'forgot-password',
    title: 'Khôi Phục Mật Khẩu Gia Tộc',
    shortTitle: 'Quên mật khẩu',
    audience: 'guest',
    category: 'Xác thực & Tiếp cận',
    description: 'Dành cho khách/thành viên quên mật khẩu nhận mã qua SMS/Email.',
    icon: 'lock_reset',
  },
  'reset-password': {
    id: 'reset-password',
    title: 'Đặt Lại Mật Khẩu Mới',
    shortTitle: 'Đặt lại mật khẩu',
    audience: 'guest',
    category: 'Xác thực & Tiếp cận',
    description: 'Thiết lập mật khẩu mới sau khi xác thực mã gia tộc.',
    icon: 'key',
  },
  'chon-khong-gian': {
    id: 'chon-khong-gian',
    title: 'Chọn Không Gian Dòng Họ & Nhập Mã Mời',
    shortTitle: 'Chọn Không Gian',
    audience: 'both',
    category: 'Không gian mở',
    description: 'Khách có thể chọn không gian mở để viếng thăm hoặc nhập mã mời của Trưởng họ.',
    icon: 'door_open',
  },
  'chi-tiet-di-vat': {
    id: 'chi-tiet-di-vat',
    title: 'Kỷ Vật Tiền Nhân & Bái Vọng Cụ Cố',
    shortTitle: 'Kỷ vật Cụ Cố',
    audience: 'both',
    category: 'Không gian mở',
    description: 'Cho phép con cháu ở xa và khách thập phương chiêm bái, dâng hương hoa online.',
    icon: 'military_tech',
  },
  'tuyen-tap-album': {
    id: 'tuyen-tap-album',
    title: 'Tuyển Tập Album Ký Ức & Điển Tích Dòng Họ',
    shortTitle: 'Album dòng họ',
    audience: 'both',
    category: 'Không gian mở',
    description: 'Bộ sưu tập tư liệu lịch sử, đại lễ giỗ tổ công khai để hậu thế tìm hiểu cội nguồn.',
    icon: 'collections_bookmark',
  },

  // === NHÓM USER (Dành cho thành viên chính thức, con cháu đã đăng nhập, quản trị dòng họ) ===
  'tong-quan-pha-he': {
    id: 'tong-quan-pha-he',
    title: 'Bảng Điều Khiển Tổng Quan Phả Hệ',
    shortTitle: 'Tổng quan phả hệ',
    audience: 'user',
    category: 'Quản trị Phả hệ',
    description: 'Thống kê thế hệ, danh bạ chi phái, ngày giỗ sắp tới và tình hình kết nối con cháu.',
    icon: 'dashboard',
  },
  'cay-pha-he-25d': {
    id: 'cay-pha-he-25d',
    title: 'Cây Gia Phả Không Gian Chiều Sâu 2.5D',
    shortTitle: 'Cây phả hệ 2.5D',
    audience: 'user',
    category: 'Quản trị Phả hệ',
    description: 'Cây tương tác đồ họa đa thế hệ với các liên kết phụ hệ, chính thất, kế thất nội tộc.',
    icon: 'account_tree',
  },
  'ho-so-tien-nhan': {
    id: 'ho-so-tien-nhan',
    title: 'Hồ Sơ Chi Tiết Tiền Nhân (Cụ Cố Nguyễn Văn Phúc)',
    shortTitle: 'Hồ sơ tiền nhân',
    audience: 'user',
    category: 'Quản trị Phả hệ',
    description: 'Chi tiết thế thứ, sắc phong, công trạng, phần mộ và nhánh con cháu phụng thờ.',
    icon: 'badge',
  },
  'them-thanh-vien': {
    id: 'them-thanh-vien',
    title: 'Thêm Thành Viên Mới Vào Sổ Phả',
    shortTitle: 'Thêm thành viên',
    audience: 'user',
    category: 'Quản trị Phả hệ',
    description: 'Quyền thành viên/trưởng tộc: cập nhật sinh/tử, con cháu mới chào đời vào dòng họ.',
    icon: 'person_add',
  },
  'khoi-tao-gia-toc': {
    id: 'khoi-tao-gia-toc',
    title: 'Khởi Tạo Không Gian Gia Tộc Mới',
    shortTitle: 'Khởi tạo gia tộc',
    audience: 'user',
    category: 'Thiết lập',
    description: 'Tạo cây phả hệ, đặt tên chi tộc, tỉnh thành quê quán và tôn chỉ dòng họ.',
    icon: 'create_new_folder',
  },
  'thiet-lap-gia-dinh': {
    id: 'thiet-lap-gia-dinh',
    title: 'Thiết Lập Không Gian Thờ Tự 6 Bước & Bàn Thờ Hôm Nay',
    shortTitle: 'Bàn thờ hôm nay',
    audience: 'user',
    category: 'Lễ bái & Bàn thờ',
    description: 'Không gian dâng hương mỗi ngày, xem tuần rằm mùng một và sắp đặt bàn thờ điện tử.',
    icon: 'smoke_free',
  },
  'them-su-kien': {
    id: 'them-su-kien',
    title: 'Tạo Sự Kiện Giỗ Chạp & Lễ Tiết Mới',
    shortTitle: 'Tạo lễ giỗ mới',
    audience: 'user',
    category: 'Lễ bái & Bàn thờ',
    description: 'Lên lịch ngày giỗ âm lịch, phân công ban khánh tiết và gửi thiệp giỗ số hóa.',
    icon: 'event_available',
  },
  'chi-tiet-gio-chap': {
    id: 'chi-tiet-gio-chap',
    title: 'Chi Tiết Sự Kiện Giỗ Cụ Cố & Phân Công Mâm Cỗ',
    shortTitle: 'Chi tiết giỗ chạp',
    audience: 'user',
    category: 'Lễ bái & Bàn thờ',
    description: 'Kế hoạch giỗ chạp, người đi chợ, văn khấn chuẩn, ngân sách và đóng góp cúng giỗ.',
    icon: 'restaurant_menu',
  },
  'kho-ky-uc': {
    id: 'kho-ky-uc',
    title: 'Kho Ký Ức & Kỷ Vật Nội Tộc Gia Đình',
    shortTitle: 'Kho ký ức & Kỷ vật',
    audience: 'user',
    category: 'Kho ký ức & AI',
    description: 'Lưu trữ tài liệu gia tộc mật độ cao, gia phả Hán Nôm, di cảo, ghi âm của ông bà.',
    icon: 'photo_library',
  },
  'phuc-che-ai': {
    id: 'phuc-che-ai',
    title: 'Xưởng Phục Chế Ảnh Ký Ức AI Di Sản',
    shortTitle: 'Phục chế AI',
    audience: 'user',
    category: 'Kho ký ức & AI',
    description: 'Công cụ AI nâng cấp ảnh cũ, khử nứt rách, phục dựng trang phục gấm vóc tổ tiên.',
    icon: 'auto_fix_high',
  },
  'dang-phuc-che': {
    id: 'dang-phuc-che',
    title: 'Tiến Trình Phục Chế Ký Ức AI Trực Quan',
    shortTitle: 'Đang phục chế AI',
    audience: 'user',
    category: 'Kho ký ức & AI',
    description: 'Màn hình theo dõi 4 giai đoạn AI khôi phục ngũ quan và chi tiết di ảnh thời gian thực.',
    icon: 'hourglass_top',
  },
  'hoan-tat-phuc-che': {
    id: 'hoan-tat-phuc-che',
    title: 'Hoàn Tất & Thẩm Định Di Ảnh 4K Trước Sau',
    shortTitle: 'Hoàn tất 4K',
    audience: 'user',
    category: 'Kho ký ức & AI',
    description: 'Thanh trượt kéo đối chiếu trước/sau, kiểm định nhân diện và phê duyệt lưu vào cây phả hệ.',
    icon: 'verified',
  },
  'lich-su-phuc-che': {
    id: 'lich-su-phuc-che',
    title: 'Nhật Ký & Lịch Sử Phục Chế Ảnh AI Dòng Họ',
    shortTitle: 'Nhật ký phục chế',
    audience: 'user',
    category: 'Kho ký ức & AI',
    description: 'Quản lý kho ảnh đã phục chế, chứng thư số Trưởng họ và dung lượng lưu trữ.',
    icon: 'history',
  },
  // === MODULE BẢO TÀNG GIA BẢO & DI VẬT TỔ TIÊN ===
  'bao-tang-gia-bao': {
    id: 'bao-tang-gia-bao',
    title: 'Bảo Tàng Gia Bảo & Di Vật Tổ Tiên',
    shortTitle: 'Bảo Tàng Gia Bảo',
    audience: 'both',
    category: 'Bảo Tàng Gia Bảo',
    description: 'Trưng bày gia bảo cổ truyền, mô hình 3D 360°, bộ lọc đa dạng và bảo tồn di sản huyết thống.',
    icon: 'museum',
  },
  'hien-tang-gia-bao': {
    id: 'hien-tang-gia-bao',
    title: 'Hiến Tặng & Đăng Ký Gia Bảo Vào Bảo Tàng',
    shortTitle: 'Hiến tặng gia bảo',
    audience: 'user',
    category: 'Bảo Tàng Gia Bảo',
    description: 'Ghi danh kỷ vật vào kim phổ số, quét 3D đa góc, gắn kết tiền nhân và lưu trữ điển tích truyền khẩu.',
    icon: 'add_circle',
  },
  'chi-tiet-gia-bao': {
    id: 'chi-tiet-gia-bao',
    title: 'Chi Tiết Đồng Hồ Quả Quýt Khải Định 1922 (3D 360°)',
    shortTitle: 'Chi tiết gia bảo 3D',
    audience: 'both',
    category: 'Bảo Tàng Gia Bảo',
    description: 'Mô hình xoay 360°, chất liệu lai lịch, ghi âm lời răn dạy của Cụ Cố và chứng thư lịch sử qua 1 thế kỷ.',
    icon: 'view_in_ar',
  },
  'phan-tich-but-tich': {
    id: 'phan-tich-but-tich',
    title: 'Phân Tích & Dịch Thuật Bút Tích Chữ Viết Tay Tiền Nhân',
    shortTitle: 'Quét chữ viết tay AI',
    audience: 'user',
    category: 'Bảo Tàng Gia Bảo',
    description: 'Thị giác Hán Nôm & Quốc ngữ cổ, đối chiếu giấy dó, phiên âm AI, gợi ý từ nhòe và lưu vào gia phả.',
    icon: 'document_scanner',
  },
  // === MODULE CÂY KỶ NIỆM & BIÊN NIÊN SỬ GIA PHONG ===
  'cay-ky-niem': {
    id: 'cay-ky-niem',
    title: 'Cây Kỷ Niệm Dòng Tộc & Cột Mốc Trực Quan',
    shortTitle: 'Cây Kỷ Niệm',
    audience: 'both',
    category: 'Gia Phong & Kỷ Niệm',
    description: 'Biểu tượng cội nguồn bách niên, các mốc thời gian sinh - đăng khoa - công đức của đại gia tộc.',
    icon: 'nature_people',
  },
  'them-cot-moc': {
    id: 'them-cot-moc',
    title: 'Thêm Cột Mốc Mới Vào Cây Kỷ Niệm',
    shortTitle: 'Thêm Cột Mốc',
    audience: 'user',
    category: 'Gia Phong & Kỷ Niệm',
    description: 'Biểu mẫu ghi nhận sự kiện lịch sử, đỗ đạt, hỷ sự hoặc công đức đại trùng tu vào biên niên sử.',
    icon: 'add_location_alt',
  },
  'tu-sach-gia-phong': {
    id: 'tu-sach-gia-phong',
    title: 'Tủ Sách Gia Phong & Điển Tích Tiền Nhân',
    shortTitle: 'Tủ Sách Gia Phong',
    audience: 'both',
    category: 'Gia Phong & Kỷ Niệm',
    description: 'Kho tàng gia huấn, di cảo, câu chuyện lập ấp và những tấm gương trung hiếu lưu truyền hậu thế.',
    icon: 'auto_stories',
  },
  'bien-nien-su': {
    id: 'bien-nien-su',
    title: 'Biên Niên Sử & Niên Biểu Đại Tộc 340 Năm',
    shortTitle: 'Biên Niên Sử',
    audience: 'both',
    category: 'Gia Phong & Kỷ Niệm',
    description: 'Dòng thời gian đa thế kỷ ghi nhận từng dấu mốc thăng trầm và hưng thịnh của tổ tiên từ thời Hậu Lê.',
    icon: 'history_edu',
  },
  'cau-chuyen-gia-phong': {
    id: 'cau-chuyen-gia-phong',
    title: 'Chi Tiết Điển Tích: Chữ Tín Bên Dòng Sông Vị Hoàng',
    shortTitle: 'Điển Tích Gia Phong',
    audience: 'both',
    category: 'Gia Phong & Kỷ Niệm',
    description: 'Câu chuyện cảm động về Cụ Cố giữ vẹn chữ Tín trong giông bão, bài học làm người sáng mãi cho hậu duệ.',
    icon: 'menu_book',
  },
  // === MODULE BÀN THỜ SỐ 3D & NGHI LỄ TẾ TỰ ===
  'khong-gian-tuong-niem-3d': {
    id: 'khong-gian-tuong-niem-3d',
    title: 'Không Gian Tưởng Niệm 3D Linh Thiêng',
    shortTitle: 'Bàn Thờ Số 3D',
    audience: 'both',
    category: 'Bàn Thờ & Tưởng Niệm',
    description: 'Không gian thực tế ảo 360° phục dựng nguyên mẫu Từ đường 5 gian, dâng hoa, nghe chuông khánh chiêm bái.',
    icon: 'temple_buddhist',
  },
  'ho-so-huong-linh': {
    id: 'ho-so-huong-linh',
    title: 'Hồ Sơ Hương Linh & Bài Vị Tiền Nhân',
    shortTitle: 'Hồ Sơ Hương Linh',
    audience: 'both',
    category: 'Bàn Thờ & Tưởng Niệm',
    description: 'Bài vị sơn son thếp vàng, tiểu sử công nghiệp, nơi an táng và văn khấn riêng cho tiền bối.',
    icon: 'account_box',
  },
  'thap-huong-tri-an': {
    id: 'thap-huong-tri-an',
    title: 'Thắp Hương Tri Ân & Dâng Lễ Tiền Linh',
    shortTitle: 'Thắp Hương Tri Ân',
    audience: 'both',
    category: 'Bàn Thờ & Tưởng Niệm',
    description: 'Nghi lễ dâng nén tâm hương, chén nước, hoa sen và gửi gắm ước nguyện bình an lên án thờ tổ tiên.',
    icon: 'mode_heat',
  },
  'cam-nang-nghi-le': {
    id: 'cam-nang-nghi-le',
    title: 'Cẩm Nang Nghi Lễ & Phong Tục Cổ Truyền',
    shortTitle: 'Cẩm Nang Nghi Lễ',
    audience: 'both',
    category: 'Nghi Lễ & Giỗ Chạp',
    description: 'Kho tàng hướng dẫn mọi nghi thức tế tự, giỗ chạp, tang ma, cưới hỏi và lễ tiết chuẩn mực dòng họ.',
    icon: 'menu_book',
  },
  'chi-tiet-nghi-le': {
    id: 'chi-tiet-nghi-le',
    title: 'Đại Lễ Tế Tổ Mùng 10 Tháng Giêng (Xuân Tế)',
    shortTitle: 'Đại Lễ Tế Tổ',
    audience: 'both',
    category: 'Nghi Lễ & Giỗ Chạp',
    description: 'Trình tự 4 giai đoạn đại lễ, bài trí mâm Tam sinh, phân công ban tế và toàn văn bài văn tế cổ truyền.',
    icon: 'verified',
  },
  // === MODULE CÀI ĐẶT, QUẢN TRỊ GIA TỘC & TÀI KHOẢN CÁ NHÂN ===
  'ma-tran-phan-quyen': {
    id: 'ma-tran-phan-quyen',
    title: 'Hệ Thống Phân Cấp Vai Trò & Ma Trận Quyền Hạn Dòng Tộc',
    shortTitle: 'Phân Quyền Gia Tộc',
    audience: 'user',
    category: 'Quản Trị Gia Tộc',
    description: '5 cấp bậc vai trò định danh: Chủ không gian, Quản trị viên, Soạn phả, Đóng góp và Người xem.',
    icon: 'badge',
  },
  'quan-ly-thanh-vien': {
    id: 'quan-ly-thanh-vien',
    title: 'Quản Lý Thành Viên & Danh Bạ Dòng Tộc Chi Trực Lăng',
    shortTitle: 'Danh Bạ Thành Viên',
    audience: 'user',
    category: 'Quản Trị Gia Tộc',
    description: 'Danh sách 48 thành viên, trạng thái trực tuyến, liên kết cây phả hệ và phân quyền nhanh.',
    icon: 'groups',
  },
  'moi-thanh-vien': {
    id: 'moi-thanh-vien',
    title: 'Mời Thành Viên Mới & Gửi Thư Mời Định Danh Gia Tộc',
    shortTitle: 'Mời Thành Viên',
    audience: 'user',
    category: 'Quản Trị Gia Tộc',
    description: 'Gửi thư mời qua Email, SMS OTP, tạo link mã hóa hoặc xuất mã QR in thiệp giỗ tổ.',
    icon: 'person_add',
  },
  'thong-bao-gia-toc': {
    id: 'thong-bao-gia-toc',
    title: 'Trung Tâm Thông Báo & Tin Tức Dòng Tộc Chi Trực Lăng',
    shortTitle: 'Bản Tin Tộc Họ',
    audience: 'both',
    category: 'Quản Trị Gia Tộc',
    description: 'Thông báo giỗ chạp, hỷ sự, vinh danh khuyến học, tu bổ từ đường và cáo phó trang nghiêm.',
    icon: 'campaign',
  },
  'ho-so-ca-nhan': {
    id: 'ho-so-ca-nhan',
    title: 'Hồ Sơ Cá Nhân & Định Danh Phả Hệ (Nguyễn Trực Viễn)',
    shortTitle: 'Hồ Sơ Cá Nhân',
    audience: 'user',
    category: 'Tài Khoản Cá Nhân',
    description: 'Thông tin bản thân, tên húy, hôn phối, trực hệ 5 đời, thẻ định danh số và gia huấn truyền thừa.',
    icon: 'account_circle',
  },
  'bao-mat-tai-khoan': {
    id: 'bao-mat-tai-khoan',
    title: 'Trung Tâm An Toàn & Bảo Mật Tài Khoản (2FA)',
    shortTitle: 'Bảo Mật Tài Khoản',
    audience: 'user',
    category: 'Tài Khoản Cá Nhân',
    description: 'Xác thực hai lớp (2FA Authenticator), đổi mật khẩu, quản lý thiết bị và nhật ký đăng nhập.',
    icon: 'security',
  },
  'goi-dich-vu-ngan-quy': {
    id: 'goi-dich-vu-ngan-quy',
    title: 'Gói Dịch Vụ Số Hóa & Quỹ Phụng Điền Dòng Tộc',
    shortTitle: 'Gói Dịch Vụ & Quỹ',
    audience: 'user',
    category: 'Quản Trị Gia Tộc',
    description: 'Gói Gia Tộc Vĩnh Niên 100 năm, hạn mức đám mây, phục chế AI và sổ thu chi công đức minh bạch.',
    icon: 'workspace_premium',
  },

  // === NHÓM SUPER ADMIN / QUẢN TRỊ TRUNG ƯƠNG ===
  'admin-dang-nhap': {
    id: 'admin-dang-nhap',
    title: 'Cổng Đăng Nhập Quản Trị Hệ Thống Trung Ương',
    shortTitle: 'Admin Đăng Nhập',
    audience: 'user',
    category: 'Quản Trị Trung Ương',
    description: 'Xác thực 2FA YubiKey dành cho Ban Trị Sự & Quản Trị Viên Tối Cao.',
    icon: 'admin_panel_settings',
  },
  'admin-tong-quan': {
    id: 'admin-tong-quan',
    title: 'Bảng Điều Khiển Tổng Quan Super Admin',
    shortTitle: 'Admin Tổng Quan',
    audience: 'user',
    category: 'Quản Trị Trung Ương',
    description: 'Giám sát 1,482 không gian gia tộc, hạ tầng AI, hàng đợi phê duyệt và cảnh báo.',
    icon: 'grid_view',
  },
  'admin-nguoi-dung': {
    id: 'admin-nguoi-dung',
    title: 'Sổ Bộ Nhân Sự & Quản Lý Người Dùng',
    shortTitle: 'Admin Người Dùng',
    audience: 'user',
    category: 'Quản Trị Trung Ương',
    description: 'Quản lý 48,290 thành viên, vai trò, gói dịch vụ và định danh CCCD.',
    icon: 'group',
  },
  'admin-chi-tiet-nguoi-dung': {
    id: 'admin-chi-tiet-nguoi-dung',
    title: 'Hồ Sơ Chi Tiết Người Dùng & Quyền Phủ Quyết',
    shortTitle: 'Admin Chi Tiết User',
    audience: 'user',
    category: 'Quản Trị Trung Ương',
    description: 'Chi tiết hồ sơ thành viên, quyền Veto Trưởng tộc và kiểm soát bảo mật.',
    icon: 'person_search',
  },
  'admin-khong-gian-gia-toc': {
    id: 'admin-khong-gian-gia-toc',
    title: 'Quản Lý Không Gian Gia Tộc & Nhà Thờ Họ Toàn Quốc',
    shortTitle: 'Admin Không Gian',
    audience: 'user',
    category: 'Quản Trị Trung Ương',
    description: 'Danh bạ 1,482 từ đường, bảo vật số hóa, phân cấp chi phái và dung lượng.',
    icon: 'account_balance',
  },
  'admin-chi-tiet-khong-gian': {
    id: 'admin-chi-tiet-khong-gian',
    title: 'Chi Tiết Quản Trị Không Gian Gia Tộc',
    shortTitle: 'Admin Chi Tiết Tộc',
    audience: 'user',
    category: 'Quản Trị Trung Ương',
    description: 'Cây phả 3 chi nhánh, ban trị sự phân quyền, kho bảo vật và hòa giải tranh chấp.',
    icon: 'domain',
  },
  'admin-van-hanh-ai': {
    id: 'admin-van-hanh-ai',
    title: 'Trung Tâm Vận Hành & Hạ Tầng AI Di Sản',
    shortTitle: 'Admin Vận Hành AI',
    audience: 'user',
    category: 'Quản Trị Trung Ương',
    description: 'Cụm GPU, OCR Hán Nôm v3.2, Vision 4K và buồng thử nghiệm mô hình.',
    icon: 'memory',
  },
  'admin-tham-dinh-ai': {
    id: 'admin-tham-dinh-ai',
    title: 'Hội Đồng Thẩm Định & Kiểm Chuẩn Kết Quả AI',
    shortTitle: 'Admin Thẩm Định AI',
    audience: 'user',
    category: 'Quản Trị Trung Ương',
    description: 'Đối soát tư liệu cổ, kiểm tra dấu triện và ký số bảo chứng Viện Hán Nôm.',
    icon: 'verified',
  },
  'admin-kiem-duyet': {
    id: 'admin-kiem-duyet',
    title: 'Kiểm Duyệt Nội Dung & Tôn Nghiêm Di Sản',
    shortTitle: 'Admin Kiểm Duyệt',
    audience: 'user',
    category: 'Quản Trị Trung Ương',
    description: 'Hàng đợi xử lý vi phạm thuần phong mỹ tục, tranh chấp phả ký và từ khóa cấm.',
    icon: 'shield',
  },
  'admin-cms-cam-nang': {
    id: 'admin-cms-cam-nang',
    title: 'Hệ Thống CMS Cẩm Nang Nghi Lễ & Tri Thức Di Sản',
    shortTitle: 'Admin CMS Cẩm Nang',
    audience: 'user',
    category: 'Quản Trị Trung Ương',
    description: 'Biên tập văn khấn cổ truyền, nghi thức giỗ chạp và ấn phẩm di sản số.',
    icon: 'menu_book',
  },
  'admin-nhat-ky-audit': {
    id: 'admin-nhat-ky-audit',
    title: 'Nhật Ký Kiểm Toán Bất Biến & An Ninh Hệ Thống',
    shortTitle: 'Admin Audit Log',
    audience: 'user',
    category: 'Quản Trị Trung Ương',
    description: 'Lưu vết chữ ký số SHA-384, phiên đăng nhập và bảo mật bất biến.',
    icon: 'receipt_long',
  },
  'admin-cai-dat-he-thong': {
    id: 'admin-cai-dat-he-thong',
    title: 'Cài Đặt & Cấu Hình Hệ Thống Trung Ương',
    shortTitle: 'Admin Cài Đặt',
    audience: 'user',
    category: 'Quản Trị Trung Ương',
    description: 'Tường lửa IP Whitelist, sao lưu kép, quy chuẩn đinh bộ và kết nối viện lưu trữ.',
    icon: 'tune',
  },
};

export const GUEST_SCREENS: ScreenType[] = [
  'platform-features',
  'privacy-security',
  'pricing',
  'guest-landing',
  'chon-khong-gian',
  'login',
  'register',
  'forgot-password',
  'reset-password',
  'chi-tiet-di-vat',
  'tuyen-tap-album',
  'bao-tang-gia-bao',
  'chi-tiet-gia-bao',
  'cay-ky-niem',
  'tu-sach-gia-phong',
  'bien-nien-su',
  'cau-chuyen-gia-phong',
  'khong-gian-tuong-niem-3d',
  'ho-so-huong-linh',
  'thap-huong-tri-an',
  'cam-nang-nghi-le',
  'chi-tiet-nghi-le',
  'thong-bao-gia-toc',
];

export const USER_SCREENS: ScreenType[] = [
  'today',
  'family-calendar',
  'tong-quan-pha-he',
  'cay-pha-he-25d',
  'ho-so-tien-nhan',
  'them-thanh-vien',
  'khoi-tao-gia-toc',
  'thiet-lap-gia-dinh',
  'them-su-kien',
  'chi-tiet-gio-chap',
  'kho-ky-uc',
  'phuc-che-ai',
  'dang-phuc-che',
  'hoan-tat-phuc-che',
  'lich-su-phuc-che',
  'bao-tang-gia-bao',
  'hien-tang-gia-bao',
  'chi-tiet-gia-bao',
  'phan-tich-but-tich',
  'cay-ky-niem',
  'them-cot-moc',
  'tu-sach-gia-phong',
  'bien-nien-su',
  'cau-chuyen-gia-phong',
  'khong-gian-tuong-niem-3d',
  'ho-so-huong-linh',
  'thap-huong-tri-an',
  'cam-nang-nghi-le',
  'chi-tiet-nghi-le',
  // Admin & User Settings
  'ma-tran-phan-quyen',
  'quan-ly-thanh-vien',
  'moi-thanh-vien',
  'thong-bao-gia-toc',
  'ho-so-ca-nhan',
  'bao-mat-tai-khoan',
  'goi-dich-vu-ngan-quy',
];
